Rename smack OVERRIDE to with-lsm-smack
Using the OVERRIDE "smack" came with the use of
the layer meta-intel-iot-security.

When switching to meta-security, it conflicts with the
package name 'smack' that provide the smack user library.

Yocto was reporting the following error:
  ERROR: .../meta-security/recipes-security/smack/smack_1.3.0.bb:
         QA Issue: Recipe .../meta-security/recipes-security/smack/smack_1.3.0.bb
         has PN of "smack" which is in OVERRIDES, this can result
         in unexpected behaviour. [pn-overrides]

Change-Id: Id71b283bf1ce5682bd94bf96595eb32506acb1d5
Signed-off-by: José Bollo <jose.bollo@iot.bzh>