Fix hvacplugin cross-compilation issue due to wrong path in CMakeLists.txt
Backport from master - urgent.

This patch fixes a cross-compilation issue with hvacplugin.
The absolute path set for Boost_INCLUDE_DIRS is not
cross-compilation save.
According to https://cmake.org/Wiki/CMake:How_To_Find_Libraries
we better use find_package(Boost REQUIRED) .

Otherwise bitbake might fail with:
ERROR: QA Issue: hvacplugin: The compile log indicates that
       host include and/or library paths were used.
       Please check the log .../hvacplugin/0.1-r0/temp/log.do_compile'
       for more information. [compile-host-path]
ERROR: QA run found fatal errors. Please consider fixing them.
ERROR: Function failed: do_package_qa

Due to:
cc1plus: warning: include location "/usr/include/boost" is unsafe
for cross-compilation [-Wpoison-system-directories]

Change-Id: I114962b60fdb0162f9e9a88964705cbbba901278
Signed-off-by: Jan-Simon Möller <jsmoeller@linuxfoundation.org>